"""阶段产物 Schema 版本。"""

STAGE1_SCHEMA_VERSION = "stage1.v1"
STAGE2_SCHEMA_VERSION = "stage2.v1"
STAGE3_SCHEMA_VERSION = "stage3.v1"
STAGE4_SCHEMA_VERSION = "stage4.v1"
STAGE5_SCHEMA_VERSION = "stage5.v1"
